name: fridlev.com
description: Welcome to my personal website. Read more
meta_description: "My personal website hosted on GitHub"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /
domain_name: "http://yourblog-domain.com"
google_analytics: "UA-XXXXXXXX-X"
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url: ""
author: "Rasmus Jensen"

# Disqus config
disqus-shortname: ""
