name: fridlev.com
description: Welcome to my personal website. Read more
meta_description: "My personal website hosted on GitHub"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: rasmus.fridlev.com
domain_name: "https://rasmus.fridlev.com"
google_analytics: "UA-XXXXXXXX-X"
plugins: [jekyll-paginate]
future: true

# Details for the RSS feed generator
url: ""
author: "Rasmus Fridlev"

# Disqus config
disqus-shortname: "fridlev"